#!/usr/bin/env node
/**
 * Generate a daily briefing digest from scraped data
 */

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');

function getLatestScrape(slug) {
  const files = fs.readdirSync(dataDir)
    .filter(f => f.startsWith(slug) && f.endsWith('.json'))
    .sort()
    .reverse();
  
  if (files.length === 0) return null;
  return JSON.parse(fs.readFileSync(path.join(dataDir, files[0])));
}

function generateDigest() {
  const competitors = ['cursor', 'cognition', 'replit'];
  const digest = {
    generatedAt: new Date().toISOString(),
    competitors: []
  };

  for (const slug of competitors) {
    const data = getLatestScrape(slug);
    if (data) {
      digest.competitors.push({
        name: data.name,
        lastScraped: data.scrapedAt,
        website: data.website,
        summary: `${data.name}: ${data.website.description || 'No recent updates detected.'}`
      });
    }
  }

  // Generate markdown briefing
  let md = `# Daily Briefing - ${new Date().toLocaleDateString()}\n\n`;
  
  for (const c of digest.competitors) {
    md += `## ${c.name}\n`;
    md += `${c.summary}\n\n`;
  }

  md += `---\n*Generated by Briefing at ${digest.generatedAt}*\n`;

  const outPath = path.join(__dirname, 'digests', `${Date.now()}.md`);
  const digestDir = path.dirname(outPath);
  if (!fs.existsSync(digestDir)) fs.mkdirSync(digestDir, { recursive: true });
  
  fs.writeFileSync(outPath, md);
  console.log(md);
  console.log(`\nSaved to ${outPath}`);
}

generateDigest();
